"""empty message

Revision ID: 8320646a5bcb
Revises: a2d994cade1a
Create Date: 2024-08-09 06:32:12.233486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8320646a5bcb'
down_revision = 'a2d994cade1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send_email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_group', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send_email', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('email_group')

    # ### end Alembic commands ###
