"""empty message

Revision ID: a2d994cade1a
Revises: 
Create Date: 2024-08-09 04:15:21.219967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d994cade1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('send_email',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('attachement', sa.String(length=200), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('inputter', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('profile_image', sa.String(length=200), nullable=True),
    sa.Column('backdrop_image', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('inputter', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('email_group',
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('email_group', sa.String(length=200), nullable=True),
    sa.Column('email', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('inputter', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['users.username'], ),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_table('music',
    sa.Column('mic', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('file', sa.String(length=200), nullable=True),
    sa.Column('featuring_name', sa.String(length=200), nullable=True),
    sa.Column('featuring_image_dir', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('played', sa.Integer(), nullable=True),
    sa.Column('downloaded', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('publish', sa.Integer(), nullable=True),
    sa.Column('playlist', sa.String(length=200), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('inputter', sa.String(length=150), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('mood', sa.String(length=100), nullable=True),
    sa.Column('instrument', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('mic')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('music')
    op.drop_table('email_group')
    op.drop_table('users')
    op.drop_table('send_email')
    # ### end Alembic commands ###
